import { readFile, sendEmail } from "@cursor/automation-flow";
import { PRIMARY_EMAIL } from "./types.js";
import type { AutomationState } from "./types.js";
import { markBriefEmailed } from "./state_helpers.js";

export interface EmailBriefOptions {
  subject: string;
  markdownPath: string;
  intro?: string;
}

/**
 * Email a generated markdown educational brief to the user's primary inbox.
 * Reads the full file contents and attaches them so nothing is truncated.
 */
export async function emailEducationalBrief(
  state: AutomationState,
  options: EmailBriefOptions,
): Promise<AutomationState> {
  const markdown = await readFile(options.markdownPath);
  if (!markdown.trim()) {
    throw new Error(`Educational brief is empty: ${options.markdownPath}`);
  }

  const filename = options.markdownPath.split("/").pop() ?? "brief.md";

  await sendEmail({
    to: PRIMARY_EMAIL,
    subject: options.subject,
    body:
      options.intro ??
      "Attached is the educational brief generated by your automation.",
    attachments: [
      {
        filename,
        content: markdown,
        contentType: "text/markdown; charset=utf-8",
      },
    ],
  });

  return markBriefEmailed(state, options.markdownPath);
}
